language: scala
dist: xenial
jdk: openjdk8
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.12
  - 2.13.3
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier/v1
before_install:
  - export TZ=Australia/Canberra
script:
  - travis_retry sbt "++${TRAVIS_SCALA_VERSION}!" mimaReportBinaryIssues test
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
