language: scala
jdk: oraclejdk8
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.6
  - 2.13.0-M4
matrix:
  include:
  - scala: 2.12.6
    jdk: oraclejdk9
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_install:
  - export TZ=Australia/Canberra
script:
  - travis_retry sbt "++${TRAVIS_SCALA_VERSION}!" test
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
