language: scala
scala:
  - 2.10.6
  - 2.11.11
matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
  - scala: 2.13.0-M2
    jdk: oraclejdk8
    script: sbt ++$TRAVIS_SCALA_VERSION compile
  - dist: trusty
    group: edge
    sudo: required
    scala: 2.12.2
    jdk: oraclejdk9
    before_install:
    - cd ~
    - JDK9_URL=`curl http://jdk.java.net/9/ | grep "lin64JDK" | grep "tar.gz\"" | sed -e "s/\"/ /g" | awk '{print $5}'`
    - wget -O jdk-9_linux-x64_bin.tar.gz $JDK9_URL
    - tar -xzf jdk-9_linux-x64_bin.tar.gz
    - cd -
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - echo "sbt.version=1.0.0-RC2" > project/build.properties
    - sbt package
    - export JAVA_HOME=~/jdk-9
    - PATH=$JAVA_HOME/bin:$PATH
    - java -version
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    script:
    - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION test
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_install:
  - export TZ=Australia/Canberra
script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION javaVersionCheck test
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
addons:
  apt:
    packages:
    - oracle-java8-installer
